[package]
name = "log_processor"
version = "0.1.0"
edition = "2021"

[lib]
# This tells Rust to create a .dylib (Mac) or .so (Linux) file
crate-type = ["cdylib"] 

[dependencies]
jni = "0.21.1" # The bridge between Java and Rust